#!/bin/sh

NAMESPACE=causelist-dev
if [ -z "$1" ]; then
  echo "Must provide DUMP_NAME"
  exit 1
else
  DUMP_FILE_LOCAL="$1"
  DUMP_FILE=`basename $DUMP_FILE_LOCAL`
fi

DB_POD=$(kubectl get po -n "${NAMESPACE}" -l app.kubernetes.io/name=mongo -o Name)

echo '***' Running mongorestore
cat ${DUMP_FILE_LOCAL} | kubectl exec -n "${NAMESPACE}" -it "${DB_POD}" -- /bin/sh -c "exec mongorestore -u "\${MONGO_INITDB_ROOT_USERNAME}" -p "\${MONGO_INITDB_ROOT_PASSWORD}"  --drop --archive"

