import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
import type { Metadata } from "next";
import ThemeRegistry from "./_components/ThemeRegistry/ThemeRegistry";
import { WebVitals } from "./_components/web-vitals";
import "./index.css";

import "@fontsource/roboto/300.css";
import "@fontsource/roboto/400.css";
import "@fontsource/roboto/500.css";
import "@fontsource/roboto/700.css";
import App from "./app.tsx";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  manifest: "/manifest.webmanifest",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {/* <WebVitals /> */}
        <ThemeRegistry>
          <AppRouterCacheProvider>
            <App>{children}</App>
          </AppRouterCacheProvider>
        </ThemeRegistry>
      </body>
    </html>
  );
}
