apiVersion: v1
kind: Service
metadata:
  name: api
  labels: {{- include "causelist-stack.labels" (list . "api") | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3001
      protocol: TCP
      name: http
  selector:
    {{- include "causelist-stack.selectorLabels" (list . "api") | nindent 4 }}
