apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    {{- include "causelist-stack.labels" (list .  "website") | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    {{- include "causelist-stack.selectorLabels" (list .  "website") | nindent 4 }}
