{{ if .Values.useDevMode }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailhog
  labels:
{{ include "causelist-stack.labels" (list . "mailhog" ) | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "causelist-stack.selectorLabels" (list . "mailhog" ) | nindent 6 }}
  template:
    metadata:
      annotations:
      labels:
        {{- include "causelist-stack.selectorLabels" (list . "mailhog" ) | nindent 8 }}
    spec:
      containers:
      - name: mailhog
        image: mailhog/mailhog:latest
        ports:
        - name: http
          containerPort: 8025
        - name: smtp
          containerPort: 1025
---
apiVersion: v1
kind: Service
metadata:
  annotations:
  name: mailhog
  labels:
{{ include "causelist-stack.labels"  (list . "mailhog" ) | indent 4 }}
spec:
  ports:
  - port: 1025
    name: mailhog-smtp
  - port: 8025
    name: mailhog-http
  selector:
    {{- include "causelist-stack.selectorLabels" (list . "mailhog" ) | nindent 4 }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mailhog-ingress
  labels:
{{ include "causelist-stack.labels" (list . "mailhog" ) | indent 4 }}
  annotations:
{{- if (not (hasSuffix "tilt" .Values.ingress.appsMainDomain)) }}
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    nginx.ingress.kubernetes.io/auth-realm: 'Gid Ninjas ONLY [-_-]~'
{{- end }}
  {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
{{- if .Values.ingress.tlsEnabled }}
  tls:
    - hosts:
        - "mailhog.{{ .Values.ingress.appsMainDomain }}"
      secretName: mailhog-tls-certficates-secret
{{- end }}
  rules:
    - host: "mailhog.{{ .Values.ingress.appsMainDomain }}"
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: mailhog
                port:
                  number: 8025
{{ end }}