{{ if .Values.useDevMode }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    {{ include "causelist-stack.labels" (list . "redis" ) | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{ include "causelist-stack.labels" (list . "redis" ) | indent 6 }}
  template:
    metadata:
      labels:
        {{ include "causelist-stack.labels" (list . "redis" ) | indent 8 }}
    spec:
      containers:
      - name: redis
        image: redis
        resources:
          requests:
            cpu: 50m
            memory: 20Mi
        ports:
        - containerPort: 6379
        volumeMounts:
          - mountPath: "/data"
            name: redis-data
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-data
---
apiVersion: v1
kind: Service
metadata:
  annotations:
  name: redis
  labels:
    {{ include "causelist-stack.labels"  (list . "redis" ) | indent 4 }}
spec:
  ports:
  - port: 6379
    name: redis
  selector:
    {{- include "causelist-stack.selectorLabels" (list . "redis" ) | nindent 4 }}
---apiVersion: v1
kind: Service
metadata:
  annotations:
  name: redis-nodeport
  labels:
{{ include "causelist-stack.labels"  (list . "redis" ) | indent 4 }}
spec:
  type: NodePort
  ports:
  - port: 6379
    nodePort: 31379
    name: redis-nodeport
  selector:
    {{- include "causelist-stack.selectorLabels" (list . "redis" ) | nindent 4 }}
{{ end }}